language: csharp
solution: XLanguage.sln
install:
  - nuget restore XLanguage.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release XLanguage.sln
  - mono ./testrunner/NUnit.Runners.3.7.0/tools/nunit-console.exe ./XLanguage.Test/bin/Release/XLanguage.Test.dll
