language: csharp
solution: XLanguage.sln
install:
  - nuget restore XLanguage.sln
  - sudo apt-get install nunit-console
script:
  - msbuild /p:Configuration=Release XLanguage.sln
  - nunit-console ./XLanguage.Test/bin/Release/XLanguage.Test.dll
