using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace XLanguage.Interfaces
{
    /// <summary>
    /// Text Preprocessor
    /// </summary>
    public interface ITextPreprocessor
    {
        /// <summary>
        /// Parse a raw text or raw expression to a collect of expression component
        /// </summary>
        /// <param name="rawText">Expression in raw text</param>
        /// <returns>A map</returns>
        string Process(string rawText);
        /// <summary>
        /// Parse a raw text or raw expression to a collect of expression component based on result of before text preprocessor
        /// </summary>
        /// <param name="beforeResult">A map generated by before text preprocessor</param>
        /// <param name="rawText">Expression in raw text</param>
        /// <returns>A map</returns>
        string Process(string beforeResult, string rawText);
    }
}
