using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Text.RegularExpressions;

using XLanguage.Interfaces;

namespace XLanguage.Preprocessor
{
    /// <summary>
    /// Get number components in expression text
    /// </summary>
    public class NumberPreprocessor : ITextPreprocessor
    {
        /// <summary>
        /// Store all expression component in the order
        /// </summary>
        private SortedDictionary<float,ExpressionComponent> components;

        /// <summary>
        /// Extract number in expression text
        /// </summary>
        public NumberPreprocessor()
        {
            components = new SortedDictionary<float,ExpressionComponent>();
        }

        /// <summary>
        /// List of components which was collected by this preprocessor
        /// </summary>
        public SortedDictionary<float,ExpressionComponent> Components { get => components; set => components = value; }

        /// <summary>
        /// Main process
        /// </summary>
        /// <param name="rawText">Expression text</param>
        /// <returns>A map</returns>
        public string Process(string rawText)
        {
            string result = "";
            for(int i = 0; i < rawText.Length; i++)
            {
                result += TagCat.NTH;
            }
            return Process(result, rawText);
        }
        /// <summary>
        /// Main process
        /// </summary>
        /// <param name="beforeResult">A map generated by before preprocessor</param>
        /// <param name="rawText">Expression text</param>
        /// <returns>A map</returns>
        public string Process(string beforeResult, string rawText)
        {
            string result = "";
            List<string> resultList = new List<string>();
            for(int i = 0; i < beforeResult.Length; i++)
            {
                resultList.Add(beforeResult[i].ToString());
            }
            MatchCollection collection = Regex.Matches(rawText, "[-]?\\d+(?:\\.\\d+)*");
            foreach(Match match in collection)
            {
                if (resultList[match.Index] != TagCat.STRING)
                {
                    components.Add(match.Index, new Operands.NumberOperand(match.Value));
                }
                for (int i = match.Index; i < match.Length + match.Index; i++)
                {
                    if (resultList[i] != TagCat.STRING)
                    {
                        resultList[i] = TagCat.NUM;
                    }
                }
            }
            for(int i = 0; i < resultList.Count; i++)
            {
                result += resultList[i];
            }
            return result;
        }
    }
}
